districts:
- name: Ampara
  model_file: models/Ampara_RandomForest.pt
- name: Anuradhapura
  model_file: models/Anuradhapura_RandomForest.pt
- name: Badulla
  model_file: models/Badulla_TransformerModel.pt
- name: Batticaloa
  model_file: models/Batticaloa_RandomForest.pt
- name: Colombo
  model_file: models/Colombo_RegressionModel.pt
- name: Galle
  model_file: models/Galle_RegressionModel.pt
- name: Gampaha
  model_file: models/Gampaha_ARIMA.pt
- name: Hambantota
  model_file: models/Hambantota_ARIMA.pt
- name: Jaffna
  model_file: models/Jaffna_CatBoostModel.pt
- name: Kalutara
  model_file: models/Kalutara_RandomForest.pt
- name: Kandy
  model_file: models/Kandy_TransformerModel.pt
- name: Kegalle
  model_file: models/Kegalle_LightGBMModel.pt
- name: Kilinochchi
  model_file: models/Kilinochchi_RegressionModel.pt
- name: Kurunegala
  model_file: models/Kurunegala_AutoARIMA.pt
- name: Mannar
  model_file: models/Mannar_LinearRegressionModel.pt
- name: Matale
  model_file: models/Matale_LinearRegressionModel.pt
- name: Matara
  model_file: models/Matara_CatBoostModel.pt
- name: Monaragala
  model_file: models/Monaragala_AutoARIMA.pt
- name: Mullaitivu
  model_file: models/Mullaitivu_XGBModel.pt
- name: NuwaraEliya
  model_file: models/NuwaraEliya_CatBoostModel.pt
- name: Polonnaruwa
  model_file: models/Polonnaruwa_TransformerModel.pt
- name: Puttalam
  model_file: models/Puttalam_RandomForest.pt
- name: Ratnapura
  model_file: models/Ratnapura_TransformerModel.pt
- name: Trincomalee
  model_file: models/Trincomalee_RandomForest.pt
- name: Vavuniya
  model_file: models/Vavuniya_RandomForest.pt
